### ISSUE TITLE
Template for weekly

### ISSUE THREAD

**Issue by lisah2u** [ub-idia640-2016/course-materials#2]
In case the rubric seems confusing, I've added an example template here: https://github.com/ub-idia640-2016/course-materials/blob/master/weekly-rubric-example.md

Lisa

@ub-idia640-2016/students

**Comment by WaltLivingston** [comment]
Thanks.  I'm sure this will be helpful.  Coincidentally, as you wrote this,
Paypal was refunding me the purchase price I paid for _Ware._  I'm in the
library now, looking up the info to see if there might be one in the stacks
(or failing that, somewhere in UMS for interlibrary loan) I can use for the
Wed. assignment.  I'm asking for an extension on the assignment until I can
acquire the book.

Walt Livingston
